### ISSUE TITLE
Add a webhook to Read The Docs

### ISSUE THREAD

**Issue by Sayam753** [wildfirepy/wildfirepy#48]
As discussed in riot, to automate rebuilding of docs for latest changes, wildfirepy needs to create an account at Read The Docs. Also attach a webhook from GitHub settings.

**Comment by Raahul-Singh** [comment]
Wanna take it up yourself? @Sayam753?

**Comment by Sayam753** [comment]
Sure. What's the name of domain for our organisation?

**Comment by Raahul-Singh** [comment]
wildfirepy.org

@krisastern
Tagging you just for your blessings :)

**Comment by Sayam753** [comment]
Lovely ❤️

**Comment by Sayam753** [comment]
Hi @Raahul-Singh .
We need to create an account at https://readthedocs.org/accounts/login/. What email ID should be use?

**Comment by Raahul-Singh** [comment]
wildfirepydev@gmail.com

**Comment by Sayam753** [comment]
Hi @Raahul-Singh 
One last thing. Can I get access to the repo settings, settings of domain name and access to this gmail? Otherwise it will be a lot of asking the respective owners to configure things!

**Comment by Raahul-Singh** [comment]
Join the teams! They have access :)

**Comment by Sayam753** [comment]
On Riot?

**Comment by ram-nad** [comment]
What are we using for docs?

**Comment by ram-nad** [comment]
Can we do with one of our custom repos and configure it to use Github pages?

**Comment by Sayam753** [comment]
Docs for keeping track of documentation of various releases but majorly to rebuild docs after every commit in master branch. In my view, Github Pages rebuild themselves based on markdown files. But sphinx rebuilds from docstrings mentioned in `rst` files. So there are two options in front of us - 
1. Configure ReadTheDocs setup to rebuild docs using sphinx. (I favour this and most of the python projects favour this).
2. Configure a GitHub action to run `make html` command in `docs` directory. This will lead to creation of static HTML pages from docstrings. These pages can be directly accessed by GitHub pages. But ultimately, we will be using `sphinx` underneath the hood. And also we have to rely on themes which are supported by sphinx not the `Jekyll themes` which `GitHub pages` use.

If I sound anywhere confusing, ping me up.

**Comment by ram-nad** [comment]
I prefer to go with second one. we can have all the benefits of hosting on Github. and we can move this to our own domain easily using GitHub pages. If I am missing something let me know.

**Comment by Raahul-Singh** [comment]
@abhijeetmanhas , @kakirastern What do you think?

**Comment by kakirastern** [comment]
@Raahul-Singh I have set up a webhook for our RTD using my credentials, the Sphinx build of the docs are now building. So I considered this matter settled, and will close this issue now.
