### ISSUE TITLE
We need our own GitHub Bot

### ISSUE THREAD

**Issue by Raahul-Singh** [wildfirepy/wildfirepy#49]
Tasks
 - [x] Welcome users on PR
 - [x] Welcome users on opening Issues
 - [x] Check Changelog
 - [ ] Add something....
 - [x] Remove related actions from workflow

**Comment by ram-nad** [comment]
The bot is ready. It will be hosted by tomorrow after the final testing and then we can use it.

#### Features:
 - Welcome users when they make open an issue.
 - If the person opening issue can be assigned to issue then he/she will be assigned automatically. (This is optional and can be disabled)
 - Welcome users when they open PR.
 - Assign PR to developers on the basis of files changed. (Also optional)

#### Remaining Problem:
A changelog check can be implemented but there is a problem. Checks/Status are always tied to a specific commit (not PRs) so changelog checks will also be tied to a commit.

So, I suggest using comments instead of checks for assuring changelog.

**Comment by Raahul-Singh** [comment]
> The bot is ready. It will be hosted by tomorrow after the final testing and then we can use it.
> #### Features:
> 
>     * Welcome users when they make open an issue.
> 
>     * If the person opening issue can be assigned to issue then he/she will be assigned automatically. (This is optional and can be disabled)
> 
>     * Welcome users when they open PR.
> 
>     * Assign PR to developers on the basis of files changed. (Also optional)
> 
> 
> #### Remaining Problem:
> 
> A changelog check can be implemented but there is a problem. Checks/Status are always tied to a specific commit (not PRs) so changelog checks will also be tied to a commit.
> 
> So, I suggest using comments instead of checks for assuring changelog.

Check the latest commit for the changelog?

**Comment by Raahul-Singh** [comment]
And @FieryBlade-313 could you help with the logo?

**Comment by FieryBlade-313** [comment]
Consider it done.

**Comment by ram-nad** [comment]
@masterashu @Raahul-Singh I have also added a changelog check. It is working fine. Any suggestions on where should we host the bot.

**Comment by Raahul-Singh** [comment]
Host it

**Comment by FieryBlade-313** [comment]
@ram-nad , by logo do you mean an Avatar for the bot. Also if anyone has some suggestion on the design, I would love to listen to them

**Comment by ram-nad** [comment]
@FieryBlade-313 exactly

@Raahul-Singh Already did it. We need to configure the app to use it. Any suggestions for bot's name?

**Comment by Raahul-Singh** [comment]
@ram-nad "wildfirepy-bot" for now

**Comment by ram-nad** [comment]
I have changed the hosting platform to Heroku. Our bot is hosted here at [https://wildfirepy-bot.herokuapp.com/](https://wildfirepy-bot.herokuapp.com/). I have also made the source code public which can be found [here](https://github.com/ram-nad/GitHubBot)

Although I have tested it multiple times, I request @Raahul-Singh and @masterashu to please test it again with all the configurations. You can install apps in your own repository. We will then finally make a new GitHub App and install it in Wildfirepy.

**Comment by Raahul-Singh** [comment]
@ram-nad In the [README](https://github.com/ram-nad/GitHubBot), It isn't mentioned that the changelog checker observes the naming convention. Have you added that?

**Comment by masterashu** [comment]
@ram-nad Are you using checks or comments for changelogs checking.

https://github.com/ram-nad/GitHubBot/blob/5b6c82b44cba390624bc6eb5ea442a8a15c560d2/src/app/app.ts#L125-L132

**Comment by masterashu** [comment]
@ram-nad Good choice.
Does the changelog blog support regex

**Comment by ram-nad** [comment]
@masterashu No, it support globs though similar to the ones we use in terminal

**Comment by ram-nad** [comment]
@Raahul-Singh @masterashu So, should we install this app now? Or make any changes?

**Comment by Raahul-Singh** [comment]
> @ram-nad In the [README](https://github.com/ram-nad/GitHubBot), It isn't mentioned that the changelog checker observes the naming convention. Have you added that?

@ram-nad what about this?

**Comment by ram-nad** [comment]
Oh sorry, I never saw that. It does enforce the naming convention to some extent. For example if we write global as "changelog/*.*.rst" then it will make sure that change is made to one of the files in this format. Do we need anything else?

**Comment by ram-nad** [comment]
We can change a bot a little bit so that if we write "changelog/{ NUMBER }.\*.rst", then it will make sure that the changed file also matches the PR number. Is this what we want or something else?

**Comment by Raahul-Singh** [comment]
The first number should correspond to the PR number.
Like 49.*.rst if the PR number is 49

**Comment by ram-nad** [comment]
> We can change a bot a little bit so that if we write "changelog/{ NUMBER }.*.rst", then it will make sure that the changed file also matches the PR number. Is this what we want or something else?

Yes this.

**Comment by FieryBlade-313** [comment]
@ram-nad Still working on it, give me a day or two.

**Comment by ram-nad** [comment]
@Raahul-Singh @masterashu  We need to get this up. Are there any changes still required?

@FieryBlade-313 Is Avatar ready?

**Comment by FieryBlade-313** [comment]
@ram-nad Added a PR which contains bot avatar files.

**Comment by shivanshsen7** [comment]
Via conversation, I reckon the issue resolved, so close it please.

**Comment by kakirastern** [comment]
Actually the PR got merged only one or two weeks ago as per our IRC conversation. But thanks for reminding!
