### ISSUE TITLE
[update] update the python version in docs as well as the dependcies file 

### ISSUE THREAD

**Issue by eshandhawan51** [wildfirepy/wildfirepy#63]
The required python version in docs is 3.5 where as the required version is 3.6, It needs to be changed. The python version also requires to be updated in the dependencies file as I tried to install with a lower python version I t shows the error 
`ERROR: Package u'wildfirepy' requires a different Python: 2.7.17 not in '>=3.5'`
It should rather show 3.6 instead of 3.5

**Comment by mehra-deepak** [comment]
can anyone please elaborate on this , does doc in here means the docs folder as in, 

```wildfirepy\docs```

if so then i could not find any such thing or maybe figure it out , seems like a doable good first issue but probably need some keen understanding with it :D

**Comment by kakirastern** [comment]
Let me take care of this without a PR soon...

**Comment by eshandhawan51** [comment]
I think this issue can be closed :)

**Comment by kakirastern** [comment]
Thanks @eshandhawan51
