### ISSUE TITLE
Add dependencies to install_requires in setup.cfg from requirements.txt

### ISSUE THREAD

**Issue by kakirastern** [wildfirepy/wildfirepy#72]
For the RTD build to be successful we will need to add to `install_requires` under `[options]` in "setup.cfg" the dependencies that should be there but currently are not. Right now the full dependency list can be found in the file "requirements.txt".

**Comment by bestpal97** [comment]
I'm doing this

**Comment by Raahul-Singh** [comment]
Go ahead!
