### ISSUE TITLE
Data folder is not automatically created on Windows

### ISSUE THREAD

**Issue by lisa761** [wildfirepy/wildfirepy#93]
Writing file into the disk (at the time of fetching) does not automatically create folders `/wildfirepy/data` and `/wildfirepy/data/VIIRS1KM` on Windows (Windows Subsystem for Linux).

<img width="686" alt="2020-09-11 (1)" src="https://user-images.githubusercontent.com/52909743/92878882-254f9e00-f42a-11ea-815e-36482563a170.png">

<img width="686" alt="2020-09-11" src="https://user-images.githubusercontent.com/52909743/92878892-284a8e80-f42a-11ea-86ab-8683ad7281df.png">

**Comment by kakirastern** [comment]
@lisa761 Okay if I look into this later today?

**Comment by lisa761** [comment]
Yup, it's cool!

**Comment by shreyamalviya** [comment]
@lisa761, test this?

**Comment by kakirastern** [comment]
Am thinking I am going to fix it
